"""add profile fields

Revision ID: 5e181f83718b
Revises: 
Create Date: 2026-06-29 13:25:10.210254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e181f83718b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('filiere', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('filiere')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('skills')
        batch_op.drop_column('bio')
        batch_op.drop_column('photo_filename')

    # ### end Alembic commands ###
